apiVersion: v1
kind: Service
metadata:
  name: prod-web-dchr-host
spec:
  selector:
    app: prod-web-dchr-host
  ports:
    - name: http
      protocol: TCP
      port: 7770
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-web-dchr-host
spec:
  replicas: 4
  selector:
    matchLabels:
      app: prod-web-dchr-host
  template:
    metadata:
      labels:
        app: prod-web-dchr-host
    spec:
      containers:
        - name: web-dchr-host
          image: registry.gitlab.com/dechristopher/dchr.host:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DEPLOY
              value: "prod"
            - name: PORT
              value: "80"
      imagePullSecrets:
        - name: regcred

---