apiVersion: v1
kind: Service
metadata:
  name: prod-web-dchr-host
spec:
  type: NodePort
  selector:
    app: prod-web-dchr-host
  ports:
    - name: http
      protocol: TCP
      nodePort: 30000
      port: 7770
      targetPort: 81

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-web-dchr-host
spec:
  replicas: 5
  selector:
    matchLabels:
      app: prod-web-dchr-host
  template:
    metadata:
      labels:
        app: prod-web-dchr-host
    spec:
      containers:
        - name: web-dchr-host
          image: registry.gitlab.com/dechristopher/dchr.host:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 81
              protocol: TCP
          env:
            - name: DEPLOY
              value: "prod"
            - name: PORT
              value: "81"
            - name: DEPKEY
              value: "fazboaz"

---
